### ISSUE TITLE
個人的にbotを動かす際に苦労したところのメモ

### ISSUE THREAD

**Issue by sakots** [tubo28/acnh-turnip-gspread#19]
- URLから推測できるスプレッドシートの名前　はシート名ではなくシートURLの spreadsheets/d/~~~~~~/edit　の部分。
- secret.env の各項目の = のあとに空白を入れてはいけない。
- virtualboxは6.1系では動かない。6.0.20をインストールしたら動いた。

**Comment by sakots** [comment]
ubuntu19.10上にVMでubuntuを走らせるという状況になっており、そこは私の能力不足と思われます。

**Comment by tubo28** [comment]
> secret.env の各項目の = のあとに空白を入れてはいけない。

これに関しては.envといいながらいわゆるenvファイルではなくシェルスクリプトなのが悪いです

**Comment by tubo28** [comment]
名前を `secret.sh` にします
