### ISSUE TITLE
型判定、上昇タイミング予測

### ISSUE THREAD

**Issue by tubo28** [tubo28/acnh-turnip-gspread#4]
Twitter で型判定フローチャトを見かけたのでできるかも

**Comment by sakots** [comment]
カブ価変動のアルゴリズムが解析されていますので、更に精密なのができるかも
https://hyperts.net/acnh-algorithm/

**Comment by tubo28** [comment]
📝 
これでテストデータがほぼ無限に生成できる
https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b

予測ツール https://hyperwiki.jp/acnh/kabu-tool/ のコア部分が難読化されてないので使える！優しい
https://hyperwiki.jp/thirdparty/scripts/predictions.js

**Comment by tubo28** [comment]
昔ながらの判定アルゴリズム
https://github.com/juo6442/moothumb

**Comment by tubo28** [comment]
mikebrtant 氏の JS は基本的には入力した実際の価格に矛盾しないパターンとその確率を列挙する仕組み

こんな感じで動かせる

```js
// 買値を 0, 1 に入れる
let sell_prices = [100, 100, 90, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN];
// 初めての週は四期型固定なので与える
let first_buy = false;
// 今週のパターンは前の週の条件付き確率なので与える
let previous_pattern = 3;
console.log(analyze_possibilities(sell_prices, first_buy, previous_pattern));
```

実行すると https://turnipprophet.io/ と同じ情報が出力される

[Js2Py](https://github.com/PiotrDabkowski/Js2Py) に投げたら [function*](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/function*) に未対応でエラーになったが、たぶん babel を通せばいい (TODO)


現在の情報を入力としてそれぞれの型になる確率・最大値の最大値・下限が直ちに得られるので、botの返答として出せば良さそう
そこまで分かれば具体的にいつがピークになるか分かる人には分かる
わからない人にはクローバーさんの資料を見てもらうことにしたい

**Comment by tubo28** [comment]
ピークがいつかで場合分けしてるので各期間がピークになる確率も計算しようと思えばできる

**Comment by tubo28** [comment]
予測ツールの進化が目覚ましいので #23 でツールへのURLを貼るようにしてみました
